[build]
  command = "npm install && pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/generate-report"
  to = "/.netlify/functions/process-file"
  status = 200
