[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "." # Serve files from the root directory

[[redirects]]
  from = "/generate-report"
  to = "/.netlify/functions/process_file"
  status = 200 # Rewrite the request to the function without changing the URL
